fragment Game on Game {
  id
  aggregated_rating
  aggregated_rating_count
  category
  created_at
  first_release_date
  follows
  hypes
  name
  rating
  rating_count
  slug
  status
  storyline
  summary
  tags
  total_rating
  total_rating_count
  updated_at
  url
  version_title
  checksum
}
