query GameDetails(
  $where: GamesWhereInput
  $imageType: ImageTypeEnum
) {
  game(where: $where) {
    ...Game
    screenshots {
      ...Screenshot
    }
    artworks {
      ...Artwork
    }
    cover {
      ...Cover
    }
    # platforms {
    #   ...Platform
    # }
    genres {
      ...Genre
    }
    game_modes {
      ...GameMode
    }
    similar_games {
      ...Game
      cover {
        ...Cover
      }
    }
    videos {
      ...GameVideo
    }
    involved_companies {
      ...InvolvedCompany
      company {
        ...Company
      }
    }
  }
}
