query Games(
  $where: GamesWhereInput
  $sort: GamesSortInput
  $limit: Int
  $offset: Int
  $imageType: ImageTypeEnum
  $platformLogo: ImageTypeEnum
) {
  games(where: $where, sort: $sort, limit: $limit, offset: $offset) {
    ...Game
    screenshots {
      ...Screenshot
    }
    artworks {
      ...Artwork
    }
    cover {
      ...Cover
    }
    platforms {
      ...Platform
      platform_logo {
        ...PlatformLogo
      }
    }
  }
}
